### ISSUE TITLE
Nomenclature Changes

### ISSUE THREAD

**Issue by simonwiles** [sul-cidr/patent_data_extractor#4]
@gmoore016 

1. **Changing the main branch for the repo:**
    I'd like to change the name of the branch from `master` → `main` -- I'm going through and doing this for all my repos, but it might cause a issue with your fork, and I don't want to create extra problems for you.  If you're willing to update the remote-tracking origins on your fork, I can send you command line instructions.  Other options include making sure your additions are merged upstream and then nuking your repo and re-forking, or just leaving it as it is, for now at least.

2. **Changing some of the keywords in the YAML config:**
    Now that these affordances are maturing a little, the initial keywords I chose don't seem terribly helpful, and I was thinking it might be good to replace them with something a bit more semantically useful.  Something like this, perhaps?
    * `enum_type` → `constant_value`?
    * `enum_map` → `value_map`?

    Or perhaps you have better ideas?  Suggestions or other feedback very welcome!

3. **Distinguishing keys (XPath expressions) from keywords:**
    Looking at the YAML files I think they'd be more readable if the (burgeoning vocabulary of) keywords were easier to distinguish from the XPath expressions that serve as the keys to the XML files.
    * `__keyword__`?
    * `KEYWORD`?
    * `_keyword`?

    I think I'm leaning towards `__KEYWORD__`, actually, so that something like
    ````yaml
    ### Continuations
    subdoc-bibliographic-information/continuity-data/continuations/continuation-of/parent-child/parent:
      entity: related_document
      fields:
        # These values are fixed for all related documents found at this location
        document-id:
          - fieldname: type
            enum_type: continuation
          - fieldname: relationship
            enum_type: parent

        # These vary from record to record
        document-id/kind-code: kind_code
        document-id/doc-number: doc_number
        document-id/document-date: date
        document-id/country-code: country_code
        parent-status: status
    ````
    would become:
    ````yaml
    ### Continuations
    subdoc-bibliographic-information/continuity-data/continuations/continuation-of/parent-child/parent:
      __ENTITY__: related_document
      __FIELDS__:
        # These values are fixed for all related documents found at this location
        document-id:
          - __FIELDNAME__: type
            __CONSTANT_VALUE__: continuation
          - __FIELDNAME__: relationship
            __CONSTANT_VALUE__: parent

        # These vary from record to record
        document-id/kind-code: kind_code
        document-id/doc-number: doc_number
        document-id/document-date: date
        document-id/country-code: country_code
        parent-status: status
    ````
   I'd welcome your input on whether this represents an improvement or not!

Feel free to respond here or on email if you have anything you'd like to comment on.

Thanks!
